//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusResevration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resevration
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public string PickPlace { get; set; }
        public string DropPlace { get; set; }
        public string CurrentStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
